### ISSUE TITLE
Bug screen on Nem wallet beta 1.4.13

### ISSUE THREAD

**Issue by tylius78** [NotEnoughMods/NEM-API#9]
Hello i detected a bug on nano wallet beta 1.4.13
with window 7 and google chrome after a while in one node when you swith of node and go to dashboard  then in confirmed a screen part move or shake.
While nothing in unconfirmed.
Its a bug screen.

link of the video https://youtu.be/X6RueO0jXXc
here my wallet for some bounty
Best regards
i can remove the video after problem sovled
ND4BRL-ECS75C-2SE2IN-TSZ6F3-EJXTWA-7BADV4-2J75

**Comment by Pyker** [comment]
Uh... You posted in the wrong issue tracker. This is for Not Enough Mods (https://notenoughmods.com/)
